[CIR][CIRDataLayout]moving CIRDataLayout to MLIRCIR (#693)
fix build failure 
undefined reference to
`cir::CIRDataLayout::CIRDataLayout(mlir::ModuleOp)'
by breaking circular dependency caused by the fact CIRDataLayout was in
CIR Codegen